apiVersion: v1
kind: ConfigMap
metadata:
  name: info-config
data:
  POSTGRES_HOST: "192.168.0.106"
  POSTGRES_PORT: "5555"
  POSTGRES_DB_NAME: "speaker"
  POSTGRES_PASSWORD: "root"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-deployment
  labels:
    app: info
spec:
  replicas: 3
  selector:
    matchLabels:
      app: info
  template:
    metadata:
      labels:
        app: info
    spec:
      containers:
      - name: info
        image: mytyan/info:0.0.1
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: info-config
                key: POSTGRES_HOST
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: info-config
                key: POSTGRES_PORT
          - name: POSTGRES_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: info-config
                key: POSTGRES_DB_NAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: info-config
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: info-service
spec:
  selector:
    app: info
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080