services:
  postgres-db:
    image: postgres:15.1-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: speaker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

volumes:
  postgres-data:
    name: postgres-data
networks:
  db-network:
    name: db-network