services:
  postgres-db:
    image: postgres:15.1-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: speaker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
  app:
    image: info:0.0.1
    ports:
      - 8081:8080
    environment:
      POSTGRES_HOST: postgres-db    #alias of db network. Networks of this service probably the same.
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: speaker
      POSTGRES_PASSWORD: root
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres-data:
    name: postgres-data
networks:
  app-network:
    name: app-network